name: webstorage
version: 1.2.0

description: Services for interacting with the Web Storage. An event-based API to manage storage changes.
homepage: https://dev.belin.io/webstorage.dart
issue_tracker: https://github.com/cedx/webstorage.dart/issues
repository: https://github.com/cedx/webstorage.dart

environment:
  sdk: '>=2.7.0 <3.0.0'

dependencies:
  json_annotation: ^3.0.1

dev_dependencies:
  build_runner: ^1.8.0
  build_test: ^0.10.12
  build_web_compilers: ^2.9.0 # 2.10.0
  coverage: ^0.13.9
  coveralls: ^5.7.0
  grinder: ^0.8.4
  json_serializable: ^3.3.0
  test: ^1.14.2
