name: webstorage
version: 2.0.0

description: Services for interacting with the Web Storage. An event-based API to manage storage changes.
homepage: https://docs.belin.io/webstorage.dart
issue_tracker: https://git.belin.io/cedx/webstorage.dart/issues
repository: https://git.belin.io/cedx/webstorage.dart

environment:
  sdk: ">=2.8.0 <3.0.0"

dev_dependencies:
  build_runner: ^1.10.0
  build_test: ^1.0.0
  build_web_compilers: ^2.11.0
  coverage: ^0.13.9
  coveralls: ^5.8.0
  test: ^1.14.6
