name: webstorage
version: 1.0.0

author: Cédric Belin <cedric@belin.io>
description: Services for interacting with the Web Storage. An event-based API to manage storage changes.
documentation: https://dev.belin.io/webstorage.dart/api
homepage: https://dev.belin.io/webstorage.dart
issue_tracker: https://github.com/cedx/webstorage.dart/issues
repository: https://github.com/cedx/webstorage.dart

environment:
  sdk: '>=2.6.0 <3.0.0'

dependencies:
  json_annotation: ^3.0.0

dev_dependencies:
  build_runner: ^1.7.2
  build_test: ^0.10.9
  build_web_compilers: ^2.7.1
  grinder: ^0.8.3
  json_serializable: ^3.2.3
  test: ^1.9.4
