name: webstorage
version: 2.0.0

description: Services for interacting with the Web Storage. An event-based API to manage storage changes.
homepage: https://cedx.github.io/webstorage.dart
issue_tracker: https://github.com/cedx/webstorage.dart/issues
repository: https://github.com/cedx/webstorage.dart

environment:
  sdk: ">=2.10.0 <3.0.0"

dev_dependencies:
  coverage: ^0.14.1
  coveralls: ^5.10.0
  test: ^1.15.4
